/*
GRUPO 1 INTEGRANTES:
- #20021003480 KATTIA VANESSA GONZALES GALVEZ
- #20091012687 JOAQUIN ISAI SALGADO DÁVILA
- #20101010369 SANDRA PRISCILA CUBAS RIVERA
- #20141011708 KENET FRANCISCO ORELLANA MEZA
- #20161003613 OWENN ALEXIS CHAVARRIA RIVERA
*/

-- EJERCICIO #1

SET SERVEROUTPUT ON;

DECLARE 
  NOMBRE_ALIMENTO ALIMENTOS.NOMBRE%TYPE;
  CODIGO_ALIMENTO NUTRIENTESXALIMENTO.ALIMENTOID%TYPE;
  COSTO_ALIMENTO ALIMENTOS.COSTO%TYPE;
  CURSOR C_INFO_DG IS SELECT ALIMENTOS.NOMBRE, NUTRIENTESXALIMENTO.ALIMENTOID, ALIMENTOS.COSTO FROM ALIMENTOS
  INNER JOIN NUTRIENTESXALIMENTO ON ALIMENTOS.ALIMENTOID = NUTRIENTESXALIMENTO.ALIMENTOID
  WHERE NUTRIENTEID='78137SA';
BEGIN

    OPEN C_INFO_DG; -- C_INFO_DG ES EL IDENTIFICADOR DE NUESTRO CURSOR
    
    LOOP
       FETCH  C_INFO_DG INTO NOMBRE_ALIMENTO, CODIGO_ALIMENTO, COSTO_ALIMENTO;
       DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL ALIMENTO ES: '||NOMBRE_ALIMENTO);
       DBMS_OUTPUT.PUT_LINE('EL CÓDIGO DEL ALIMENTO ES: '||CODIGO_ALIMENTO);
       DBMS_OUTPUT.PUT_LINE('EL COSTO DEL ALIMENTO ES: '||COSTO_ALIMENTO);
       DBMS_OUTPUT.PUT_LINE(CHR(13));
       EXIT WHEN C_INFO_DG%NOTFOUND;
    END LOOP;
    
    CLOSE C_INFO_DG;
END;

-- CONSULTA PARA VALIDAR QUE EFECTIVAMENTE EL BLOQUE ANÓNIMO MUESTRA LO SOLICITADO EN EL INCISO.

  SELECT ALIMENTOS.NOMBRE, NUTRIENTESXALIMENTO.ALIMENTOID, ALIMENTOS.COSTO FROM ALIMENTOS
  INNER JOIN NUTRIENTESXALIMENTO ON ALIMENTOS.ALIMENTOID = NUTRIENTESXALIMENTO.ALIMENTOID
  WHERE NUTRIENTEID='78137SA';