/*
GRUPO 1 INTEGRANTES:
- #20021003480 KATTIA VANESSA GONZALES GALVEZ
- #20091012687 JOAQUIN ISAI SALGADO DÁVILA
- #20101010369 SANDRA PRISCILA CUBAS RIVERA
- #20141011708 KENET FRANCISCO ORELLANA MEZA
- #20161003613 OWENN ALEXIS CHAVARRIA RIVERA
*/

-- EJERCICIO #2

SET SERVEROUTPUT ON;

DECLARE

  TYPE FILA IS RECORD (
  CODIGO_ANIMAL ANIMALES.ANIMALID%TYPE,
  NOMBRE_ANIMAL ANIMALES.NOMBRE%TYPE,
  ESPECIE_ANIMAL ANIMALES.ESPECIE%TYPE,
  PESO_ANIMAL ANIMALES.PESO%TYPE,
  FECHA_TOMA TOMAS.FECHA%TYPE,
  HORA_TOMA TOMAS.HORA%TYPE,
  DESCRIPCION_DIETA DIETA.DESCRIPCION%TYPE,
  FECHA_INICIO_DIETA ANIMALXDIETA.FECHAINICIO%TYPE,
  FECHA_FINAL_DIETA ANIMALXDIETA.FECHAFINAL%TYPE
  );
  TYPE TABLA_INFORMACION_ANIMALES IS TABLE OF FILA INDEX BY PLS_INTEGER;
  DATOS_ANIMALES TABLA_INFORMACION_ANIMALES;
  ITERACION NUMBER(10):=0;
  /* 

  LA CONDICION PARA RETORNAR RETORNAR LOS ANIMALES DE 2003 y 2005 ES:
  
  PARA 2003 --> WHERE ANIMALID='A-01-D1';
  
  PARA 2005 --> WHERE ANIMALID='K-12-DA';

  */
BEGIN

    SELECT ANIMALES.ANIMALID, ANIMALES.NOMBRE, ANIMALES.ESPECIE, ANIMALES.PESO, TOMAS.FECHA, TOMAS.HORA, 
    DIETA.DESCRIPCION, ANIMALXDIETA.FECHAINICIO, ANIMALXDIETA.FECHAFINAL BULK COLLECT INTO DATOS_ANIMALES FROM ANIMALES
    INNER JOIN TOMAS ON TOMAS.ANIMALID = ANIMALES.ANIMALID
    INNER JOIN ANIMALXDIETA ON ANIMALXDIETA.ANIMALID = ANIMALES.ANIMALID
    INNER JOIN DIETA ON ANIMALXDIETA.DIETAID = DIETA.DIETAID
    WHERE ANIMALID='A-01-D1'; -- CONDICIÓN QUE DETERMINA EL ANIMAL EN EL AÑO 2003
    DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE REGISTROS ES: '||SQL%ROWCOUNT); -- CANTIDAD DE REGISTROS ENCONTRADOS
    
    WHILE (ITERACION<SQL%ROWCOUNT)LOOP
       DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL ANIMAL ES: '||DATOS_ANIMALES(ITERACION+1).CODIGO_ANIMAL);
       DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL ANIMAL ES: '||DATOS_ANIMALES(ITERACION+1).NOMBRE_ANIMAL);
       DBMS_OUTPUT.PUT_LINE('LA ESPECIE DEL ANIMAL ES: '||DATOS_ANIMALES(ITERACION+1).ESPECIE_ANIMAL);
       DBMS_OUTPUT.PUT_LINE('EL PESO DEL ANIMAL ES: '||DATOS_ANIMALES(ITERACION+1).PESO_ANIMAL);
       DBMS_OUTPUT.PUT_LINE('LA FECHA DE LA TOMA FUE EL: '||DATOS_ANIMALES(ITERACION+1).FECHA_TOMA);
       DBMS_OUTPUT.PUT_LINE('LA HORA DE LA TOMA FUE A LAS: '||DATOS_ANIMALES(ITERACION+1).HORA_TOMA);
       DBMS_OUTPUT.PUT_LINE('LA DIETA CONSISTE EN: '||DATOS_ANIMALES(ITERACION+1).DESCRIPCION_DIETA);
       DBMS_OUTPUT.PUT_LINE('LA FECHA DEL INICIO DE LA DIETA FUE EL: '||DATOS_ANIMALES(ITERACION+1).FECHA_INICIO_DIETA);
       DBMS_OUTPUT.PUT_LINE('LA FECHA DEL FINAL DE LA DIETA FUE EL: '||DATOS_ANIMALES(ITERACION+1).FECHA_FINAL_DIETA);
       DBMS_OUTPUT.PUT_LINE(CHR(13));
       ITERACION:=ITERACION+1;
    END LOOP;

END;

-- CONSULTA PARA VALIDAR QUE EFECTIVAMENTE EL BULK COLLECT MUESTRA LO SOLICITADO EN EL INCISO.

  SELECT ANIMALES.ANIMALID, ANIMALES.NOMBRE, ANIMALES.ESPECIE, ANIMALES.PESO, TOMAS.FECHA, TOMAS.HORA, 
  DIETA.DESCRIPCION, ANIMALXDIETA.FECHAINICIO, ANIMALXDIETA.FECHAFINAL FROM ANIMALES
  INNER JOIN TOMAS ON TOMAS.ANIMALID = ANIMALES.ANIMALID
  INNER JOIN ANIMALXDIETA ON ANIMALXDIETA.ANIMALID = ANIMALES.ANIMALID
  INNER JOIN DIETA ON ANIMALXDIETA.DIETAID = DIETA.DIETAID
  WHERE ANIMALID='A-01-D1';

