/*
GRUPO 1 INTEGRANTES:
- #20021003480 KATTIA VANESSA GONZALES GALVEZ
- #20091012687 JOAQUIN ISAI SALGADO DÁVILA
- #20101010369 SANDRA PRISCILA CUBAS RIVERA
- #20141011708 KENET FRANCISCO ORELLANA MEZA
- #20161003613 OWENN ALEXIS CHAVARRIA RIVERA
*/

-- EJERCICIO #4

CREATE TABLE BITACORAS (
 PK_BITACORA NUMBER PRIMARY KEY,
 DESCRIPCION VARCHAR2(2000),
 FECHA_HORA TIMESTAMP,
 USUARIO VARCHAR2(100),
 OPERACION VARCHAR2(50)
);

-- SECUENCIA
CREATE SEQUENCE SQ_BITACORAS
START WITH 14
INCREMENT BY 1;

-- TRIGGER 
CREATE OR REPLACE TRIGGER TG_TOMAS
AFTER INSERT OR UPDATE ON TOMAS
FOR EACH ROW
BEGIN
  IF (INSERTING) THEN
    INSERT INTO BITACORAS VALUES (SQ_BITACORAS.NEXTVAL, 'SE REALIZO UN INSERT EN LA TABLA TOMAS, EL DATO NUEVO 
    EN EL ID ES: '||:NEW.TOMAID||', EL ANIMALID ES: '||:NEW.ANIMALID||', EL NOMBRE DEL ANIMAL ES: '||:NEW.ANIMALES||', 
    EL DIETAID ES: '||:NEW.DIETAID||', LA DIETA DEL ANIMAL ES: '||:NEW.DIETA, SYSTIMESTAMP, USER, 'OPERACION INSERT');
  END IF;
  
  IF (UPDATING) THEN 
    INSERT INTO BITACORAS VALUES (SQ_BITACORAS.NEXTVAL, 'SE REALIZO UN UPDATE EN LA TABLA TOMAS, EL NOMBRE ANTERIOR 
    DEL ANIMAL ES: '||:OLD.ANIMALES||', SU NUEVO NOMBRE ES: '||:NEW.ANIMALES||', LA DIETA ANTERIOR DEL ANIMAL ES: '||:OLD.DIETA||', 
    SU NUEVA DIETA ES: '||:NEW.DIETA, SYSTIMESTAMP, USER, 'OPERACION UPDATE');
  END IF;
END;

BEGIN
  INSERT INTO TOMAS (ANIMALID) VALUES ('K-12-SO');
END;

CREATE OR REPLACE TRIGGER TG_TOMAS_DIETAS_GANADERAS
AFTER INSERT OR UPDATE ON TOMAS
FOR EACH ROW
BEGIN
  IF (INSERTING) THEN
    INSERT INTO BITACORAS VALUES (SQ_BITACORAS.NEXTVAL, 'SE REALIZO UN INSERT EN LA TABLA TOMAS, EL DATO NUEVO 
    EN EL ID ES: '||:NEW.TOMAID||', EL ANIMALID ES: '||:NEW.ANIMALID||', EL DIETAID ES: '||:NEW.DIETAID, 
    SYSTIMESTAMP, USER, 'OPERACION INSERT');
  END IF;
  
  IF (UPDATING) THEN 
    INSERT INTO BITACORAS VALUES (SQ_BITACORAS.NEXTVAL, 'SE REALIZO UN UPDATE EN LA TABLA TOMAS, EL ANIMALID ANTERIOR 
    DEL ANIMAL ES: '||:OLD.ANIMALID||', SU NUEVO ANIMALID ES: '||:NEW.ANIMALID||', EL DIETAID ANTERIOR DEL ANIMAL ES: '||:OLD.DIETAID||', 
    SU NUEVO DIETAID ES: '||:NEW.DIETAID, SYSTIMESTAMP, USER, 'OPERACION UPDATE');
  END IF;
END;