/*
GRUPO 1 INTEGRANTES:
- #20021003480 KATTIA VANESSA GONZALES GALVEZ
- #20091012687 JOAQUIN ISAI SALGADO DÁVILA
- #20101010369 SANDRA PRISCILA CUBAS RIVERA
- #20141011708 KENET FRANCISCO ORELLANA MEZA
- #20161003613 OWENN ALEXIS CHAVARRIA RIVERA
*/

-- EJERCICIO #2

/* HABILITANDO LA SALIDA DE DATOS EN PANTALLA */
SET SERVEROUTPUT ON;

/* CREACIÓN DE PROCEDIMIENTO ALMACENADO SP TBLMUNICIPIOS */
CREATE OR REPLACE PROCEDURE SP_INSERTAR_REGISTROS_MCPIOS (NOMBRE_MCPIO VARCHAR2, ID_DEPTO IN NUMBER, NOMBRE_DEPTO VARCHAR2, 
ID_PAIS NUMBER, MSJ_ERROR OUT VARCHAR2, MSJ_EXITO OUT VARCHAR2)
IS
  CANTIDAD_REGISTROS NUMBER;
  CODIGO_DEPTO NUMBER;
BEGIN
  SELECT COUNT (*) INTO CANTIDAD_REGISTROS FROM TBLMUNICIPIOS WHERE IDDEPARTAMENTO=ID_DEPTO;
  IF (CANTIDAD_REGISTROS=1) THEN 
    INSERT INTO TBLMUNICIPIOS (NOMBREMUNICIPIO, IDDEPARTAMENTO) VALUES (NOMBRE_MCPIO, ID_DEPTO);
    COMMIT;
  
  MSJ_EXITO:='EL REGISTRO DEL MUNICIPIO FUE EXITOSO';
  ELSE 
    SP_INSERTAR_REGISTROS_DEPTOS (NOMBRE_DEPTO, CODIGO_DEPTO, ID_PAIS);
    INSERT INTO TBLMUNICIPIOS (NOMBREMUNICIPIO, IDDEPARTAMENTO) VALUES (NOMBRE_MCPIO, CODIGO_DEPTO);
    COMMIT;
    
  MSJ_EXITO:='EL REGISTRO DEL MUNICIPIO FUE EXITOSO';
  END IF;
  
  EXCEPTION
    WHEN OTHERS THEN
        MSJ_ERROR:=SQLERRM;
END;

/* BLOQUE ANÓNIMO */
DECLARE
  MSJ_ERROR VARCHAR2(500);
  MSJ_EXITO VARCHAR2(500);
BEGIN
  SP_INSERTAR_REGISTROS_MCPIOS ('Marcala', 5, 'La Paz', 1, MSJ_ERROR, MSJ_EXITO);
  DBMS_OUTPUT.PUT_LINE(MSJ_EXITO||' '||MSJ_ERROR);
END;

/* SECUENCIA PARA PROCEDIMIENTO ALMACENADO TBLMUNICIPIOS */
CREATE SEQUENCE SQ_TBLMUNICIPIOS
START WITH 9
INCREMENT BY 1;

/* TRIGGER PARA PROCEDIMIENTO ALMACENADO TBLMUNICIPIOS */
CREATE OR REPLACE TRIGGER TG_SQ_TBLMUNICIPIOS
BEFORE INSERT ON TBLMUNICIPIOS
FOR EACH ROW
DECLARE
BEGIN
  :NEW.IDMUNICIPIO:=SQ_TBLMUNICIPIOS.NEXTVAL;
END;

/* CREACIÓN DE PROCEDIMIENTO ALMACENADO SP PARA TBLDEPARTAMENTOS */
CREATE OR REPLACE PROCEDURE SP_INSERTAR_REGISTROS_DEPTOS (NOMBRE_DEPTO VARCHAR2, ID_DEPTO OUT NUMBER, ID_PAIS NUMBER)
IS

BEGIN
  INSERT INTO TBLDEPARTAMENTOS (NOMBREDEPARTAMENTO, IDPAIS) VALUES (NOMBRE_DEPTO, ID_PAIS);
  SELECT IDDEPARTAMENTO INTO ID_DEPTO FROM TBLDEPARTAMENTOS WHERE NOMBREDEPARTAMENTO=NOMBRE_DEPTO;
  COMMIT;
END;

/* SECUENCIA PARA PROCEDIMIENTO ALMACENADO SP TBLDEPARTAMENTOS */
CREATE SEQUENCE SQ_TBLDEPARTAMENTOS
START WITH 5
INCREMENT BY 1;

/* TRIGGER PARA PROCEDIMIENTO ALMACENADO TBLDEPARTAMENTOS */
CREATE OR REPLACE TRIGGER TG_SQ_TBLDEPARTAMENTOS
BEFORE INSERT ON TBLDEPARTAMENTOS
FOR EACH ROW
DECLARE
BEGIN
  :NEW.IDDEPARTAMENTO:=SQ_TBLDEPARTAMENTOS.NEXTVAL;
END;




/* CONSULTAS PARA FILAS TBLMUNICIPIOS Y TBLDEPARTAMENTOS */
SELECT * FROM TBLMUNICIPIOS WHERE NOMBREMUNICIPIO='Marcala';

SELECT * FROM TBLDEPARTAMENTOS WHERE NOMBREDEPARTAMENTO='La Paz';

/* CONSULTAS PARA LAS TABLAS TBLMUNICIPIOS Y TBLDEPARTAMENTOS */
SELECT * FROM TBLMUNICIPIOS;

SELECT * FROM TBLDEPARTAMENTOS;