/*
GRUPO 1 INTEGRANTES:
- #20021003480 KATTIA VANESSA GONZALES GALVEZ
- #20091012687 JOAQUIN ISAI SALGADO DÁVILA
- #20101010369 SANDRA PRISCILA CUBAS RIVERA
- #20141011708 KENET FRANCISCO ORELLANA MEZA
- #20161003613 OWENN ALEXIS CHAVARRIA RIVERA
*/

-- EJERCICIO #4

/* HABILITANDO LA SALIDA DE DATOS EN PANTALLA */
SET SERVEROUTPUT ON;

/* CREACIÓN DE LA FUNCIÓN PARA OBTENER LOS DATOS DE LOS HABITANTES DEL MUNICIPIO DE OJOJONA */
CREATE OR REPLACE FUNCTION FN_DATOS_MCPIO (IDMCPIO TBLHABITANTES.IDMUNICIPIO%TYPE)
RETURN SYS_REFCURSOR
IS 
  DATOS_HABS_MCPIO SYS_REFCURSOR;
BEGIN
  OPEN DATOS_HABS_MCPIO FOR SELECT IDMUNICIPIO, NOMBREHABITANTE, IDHABITANTE FROM TBLHABITANTES WHERE IDMUNICIPIO=IDMCPIO; 
  
  RETURN DATOS_HABS_MCPIO;
END;

/* IMPRIMIENDO LA CANTIDAD DE HABITANTES DEL MUNICIPIO DE OJOJONA EN EL BLOQUE ANÓNIMO */

/* SE UTILIZA EL IDMUNICIPIO=2 EN LA FUNCIÓN FN_DATOS_MCPIO(2) PARA RETORNAR 
TODOS LOS DATOS DE LOS HABITANTES CORRESPONDIENTES AL MUNICIPIO DE OJOJONA */
DECLARE
  DATOS_HABS SYS_REFCURSOR;
  HABS_MCPIOS TBLHABITANTES%ROWTYPE;
BEGIN 
  DATOS_HABS:=FN_DATOS_MCPIO(2);
  LOOP
    FETCH DATOS_HABS INTO HABS_MCPIOS;
    EXIT WHEN DATOS_HABS%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('EL NÚMERO DE ID CORRESPONDIENTE AL MUNICIPIO DE OJOJONA ES: '||HABS_MCPIOS.IDMUNICIPIO);
    DBMS_OUTPUT.PUT_LINE('EL NÚMERO DE ID CORRESPONDIENTE AL HABITANTE DE OJOJONA ES: '||HABS_MCPIOS.IDHABITANTE);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL HABITANTE DEL MUNICIPIO DE OJOJONA ES: '||HABS_MCPIOS.NOMBREHABITANTE);
    DBMS_OUTPUT.PUT_LINE(CHR(13));
  END LOOP;
END;

/* CONSULTA PARA LA TABLA TBLHABITANTES */
SELECT * FROM TBLHABITANTES;