/*
GRUPO 1 INTEGRANTES:
- #20021003480 KATTIA VANESSA GONZALES GALVEZ
- #20091012687 JOAQUIN ISAI SALGADO DÁVILA
- #20101010369 SANDRA PRISCILA CUBAS RIVERA
- #20141011708 KENET FRANCISCO ORELLANA MEZA
- #20161003613 OWENN ALEXIS CHAVARRIA RIVERA
*/

-- EJERCICIO #1

/* HABILITANDO LA SALIDA DE DATOS EN PANTALLA */
SET SERVEROUTPUT ON;

/* CREACIÓN DE LA FUNCIÓN PARA OBTENER LA CANTIDAD DE HABITANTES DEL MUNICIPIO DE OJOJONA */
CREATE OR REPLACE FUNCTION FN_CANTIDAD_HABITANTES (IDMCPIO IN NUMBER)
RETURN NUMBER
IS
  CANTIDAD_HABITANTES NUMBER;
BEGIN
  SELECT COUNT (*) INTO CANTIDAD_HABITANTES FROM TBLHABITANTES WHERE IDMUNICIPIO=IDMCPIO;
  RETURN CANTIDAD_HABITANTES;
END;

/* IMPRIMIENDO LA CANTIDAD DE HABITANTES DEL MUNICIPIO DE OJOJONA EN EL BLOQUE ANÓNIMO */

/* SE UTILIZA EL IDMUNICIPIO=2 EN LA FUNCIÓN FN_CANTIDAD_HABITANTES(2) PARA RETORNAR 
LA CANTIDAD DE HABITANTES CORRESPONDIENTES AL MUNICIPIO DE OJOJONA */
DECLARE 
  TOTAL_HABITANTES NUMBER;
BEGIN
  TOTAL_HABITANTES:=FN_CANTIDAD_HABITANTES(2);
  DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE HABITANTES QUE TIENE EL MUNICIPIO DE OJONONA SON: ' ||TOTAL_HABITANTES);
END;

/* CONSULTA PARA LA TABLA TBLHABITANTES */
SELECT * FROM TBLHABITANTES;